### PR TITLE
Proposal to improve Apache Parquet FSR and disapprove the duplicate

### LINKED ISSUE #54: Apache Parquet
http://purl.org/np/RAJdVVQVtRnX3vWa4ONUbZwEjX4Al59Wpy_FWduIhCrWs

### PR DESCRIPTION
**Pull request by rbramley**
Resolves #54 and #110

### CODE REVIEW

**Review by mabablue — APPROVED** [review]
perfect!

**Comment by rbramley** [comment]
Hi @mabablue - unfortunately I don't seem to have the necessary facilitator permissions in the FIP Wizard to be able to improve the FER or comment on it.

**Comment by mabablue** [comment]
> Hi @mabablue - unfortunately I don't seem to have the necessary facilitator permissions in the FIP Wizard to be able to improve the FER or comment on it.

you should have them now, sorry for that

**Comment by rbramley** [comment]
Contacted Shuai who improved the FER in FIP Wizard to remove the superfluous Semantic model type (on the FSR listed as issue 54). Consequently I have qualified that new nanopub and confirmed that it's qualification_np appears in find_gofair_qualified_things_x and the checkmark appears in the FIP Wizard.
The duplicate FSR listed as issue 110 was then retracted through the FIP Wizard. It had no references in FIPs (checked through the matrix).

**Pull request merged**
