### PR TITLE
improve DataOne FSR to resolve #254

### LINKED ISSUE #254: Data Observation Network for Earth
http://purl.org/np/RAU2z2ehbJpnRHujQ5WnovRc2RrSI9nn6qbJ-P4OQt_sQ

### PR DESCRIPTION
**Pull request by annefou**
FSR qualification for DataOne to resolve #254

### CODE REVIEW

**Review by mabablue — CHANGES_REQUESTED** [review]
please also add link (accessible via URL: https://search.dataone.org/data)

**Comment by annefou** [comment]
@mabablue added link to https://search.dataone.org/data in the csv file. Please review again and let me know if it is OK. 
Thanks, Anne.

**Comment by rbramley** [comment]
Have just merged in changes from another merged PR. 
This looks like it still needs part 2 of the qualification to be completed, see [F3](https://github.com/gofair-foundation/fsr_qualification/blob/main/CONTRIBUTING.md#f3-as-editor).

**Review by mabablue — COMMENTED** [review]
Please add the information in the table starting with steps do and qualify it

**Pull request merged**
