### PR TITLE
added FSR qualification

### LINKED ISSUE #278: Relations Ontology
http://purl.org/np/RAVT7rLksAMk6USGEr3zTPnkY81Mnpoxfr_6_PYKN7bN4

### PR DESCRIPTION
**Pull request by panovp**
resolves #278

### CODE REVIEW

**Comment by RubenPeeters** [comment]
Hi Pance, looks good but I can't see the updated FSR anywhere. Can you add that in the CSV? Then I will accept.

**Comment by panovp** [comment]
> Hi Pance, looks good but I can't see the updated FSR anywhere. Can you add that in the CSV? Then I will accept.

Hey Ruben, as I understood in the first step the editor does the analysis and makes the proposal and if it is accepted, in the second step I do the updates and update the 2. entries in the csv file . Or I am getting things in a wrong way :D

**Comment by RubenPeeters** [comment]
You are indeed right. I was a bit too fast while reading.

**Review by RubenPeeters — COMMENTED** [review]
Looks good to me!

**Review by RubenPeeters — APPROVED** [review]

**Review by RubenPeeters — APPROVED** [review]

**Pull request merged**
