### PR TITLE
added NP_schema accept

### LINKED ISSUE #163: NP_schema | Nanopublication Guidelines
http://purl.org/np/RAPvCHdqwhadia2W25lrx23bvxbo7RVxJ7uLlhk5ddM4U

### PR DESCRIPTION
**Pull request by mabablue**
resolves #163

### CODE REVIEW

**Review by annefou — COMMENTED** [review]
The csv was odd e.g. two rows were added. I fixed it (mostly useful if we go back in time and check).

Here, I don't fully understand why the FSR type is metadata-schema. I thought guidelines would be FAIR supporting resources "only". I guess I miss something here.

Thanks,

Anne.

**Review by mabablue — COMMENTED** [review]
the guideline is a metadata schema because it offers instructions in their composition, implementation, and use.the minimal structure of the nanopublication. It includes the NP ontology but this is described by another FSR

**Comment by mabablue** [comment]
> The csv was odd e.g. two rows were added. I fixed it (mostly useful if we go back in time and check).
> 
> Here, I don't fully understand why the FSR type is metadata-schema. I thought guidelines would be FAIR supporting resources "only". I guess I miss something here.
> 
> Thanks,
> 
> Anne.

FSR is the parent class of FER. A metadata schema is a FER and also a FSR. I think you refer to FAIR practice but this is not a practice but a specification about the structure of a nanopublication

**Comment by rbramley** [comment]
I've performed an integration merge to bring the latest changes from the main branch into this branch. It includes the new issue number column, so have populated that too.

**Comment by rbramley** [comment]
Just checked and this isn't showing as qualified yet:
image

**Pull request merged**
