### PR TITLE
Proposal to improve CC-BY-NC 2.0 FSR

### LINKED ISSUE #106: CC-BY-NC 2.0
http://purl.org/np/RAWCImVlPF6-8_6LzXaXiRYqyQQMnVq8hDwngXzuOYPyI

### PR DESCRIPTION
**Pull request by rbramley**
Resolves #106

### CODE REVIEW

**Review by annefou — COMMENTED** [review]
That is an interesting question e.g. whether we should qualify "old" version CC-BY-NC 2.0 rather than CC-BY-NC 4.0.

I would be in favour of qualifying CC-BY-NC 4.0

**Comment by burgerga** [comment]
Hmm, there are some differences of course between 2.0 and 4.0, but these differences are a bit tricky to find.

Typically I use tldrlegal to find out info about licenses but they don't have a short version for 2.0, they do have 4.0 (of course): https://www.tldrlegal.com/license/creative-commons-attribution-noncommercial-4-0-international-cc-by-nc-4-0

You can also use the [Joinup Licensing Assistant](https://joinup.ec.europa.eu/collection/eupl/solution/joinup-licensing-assistant/jla-find-and-compare-software-licenses) from the EU, but here also only version 4.0

But, that led me to the SPDX License List (https://spdx.org/licenses/, managed by the Linux Foundation), and that one is actually pretty nice, and available in e.g., RDFa, HTML, Text, and JSON :O

Maybe we should include the SPDX identifier in our License FERs as well? (@mabablue)

Having said that, I don't see the downside of qualifying CC-BY-NC 2.0, but maybe we can just generate these License FERs from the SPDX list instead...

**Comment by mabablue** [comment]
> Hmm, there are some differences of course between 2.0 and 4.0, but these differences are a bit tricky to find (they can be extracted from https://wiki.creativecommons.org/wiki/License_Versions probably)
> 
> Typically I use tldrlegal to find out info about licenses but they don't have a short version for 2.0, they do have 4.0 (of course): https://www.tldrlegal.com/license/creative-commons-attribution-noncommercial-4-0-international-cc-by-nc-4-0
> 
> You can also use the [Joinup Licensing Assistant](https://joinup.ec.europa.eu/collection/eupl/solution/joinup-licensing-assistant/jla-find-and-compare-software-licenses) from the EU, but here also only version 4.0
> 
> But, that led me to the SPDX License List (https://spdx.org/licenses/, managed by the Linux Foundation), and that one is actually pretty nice, and available in e.g., RDFa, HTML, Text, and JSON :O (https://github.com/spdx/license-list-data)
> 
> Maybe we should include the SPDX identifier in our License FERs as well? (@mabablue)
> 
> Having said that, I don't see the downside of qualifying CC-BY-NC 2.0, but maybe we can just generate these License FERs from the SPDX list instead...

I would qualify both versions, people might have used the one or the other one. For your suggestion Gerhard, I ask you to write an email to Tobias, how we can write a script to avoid doing this automatically, but there are for sure some overlaps....

**Review by annefou — APPROVED** [review]
Right. Based on Barbara's input, I think we can approve this PR.

**Comment by RubenPeeters** [comment]
My apologies, I misunderstood and merged this already.

**Pull request merged**
