### PR TITLE
Add BioStudies (#44) qualification info

### LINKED ISSUE #44: BioStudies
http://purl.org/np/RA5oWuJZQ5xqYu0lzGTLfMkrIqF5IKIlHDYr6NHl5ffXk

### PR DESCRIPTION
**Pull request by burgerga**
Resolves #44 

Created using FIP wizard from FAIRsharing. Unsure if the `doap:implements` make sense, could remove this in the FIP wizard I think. 

Also test case for the csv-to-md Github action.

### CODE REVIEW

**Comment by burgerga** [comment]
Hmm, not triggered yet, I'll try to make some changes

**Comment by mabablue** [comment]
> Resolves #44
> 
> Created using FIP wizard from FAIRsharing. Unsure if the `doap:implements` make sense, could remove this in the FIP wizard I think.
> 
>  Also test case for the csv-to-md Github action.

I  think it should be improved and the link for implements deleted

**Comment by burgerga** [comment]
@rbramley I think it not triggering might be caused by this: https://stackoverflow.com/a/67551255/1439843
I will investigate further

**Comment by rbramley** [comment]
Well found, yes that does sound quite likely. 
We can try generating a new fine-grained PAT tomorrow that is scoped just for this repo.

**Review by mabablue — APPROVED** [review]

**Pull request merged**
